### ISSUE TITLE
Explore a review workflow for ETD submissions

### ISSUE THREAD

**Issue by uconnjeustis** [islandora-interest-groups/Islandora-IR-Interest-Group#12]
At UConn, our Graduate School needs to review all ETD submissions. As we use Fedora/Islandora in a consortium environment, using the inactive state or the simple workflow doesn't make sense for us. It would be great to have a way to have an ingest that is reviewed by someone and then approved for submission. This replicates a workflow integral in BePress' Digital Commons and would help others move from that platform to Islandora.

**Comment by dmoses** [comment]
Jenn, what might be useful to start with is the existing workflow you have now. Perhaps a flow diagram with the who does what at each step?  Are there multiple steps/approvals? If the step is review > approve ... then what you describe is what the simple workflow module does.
Donald

**Comment by uconnjeustis** [comment]
Donald, The liaison with our Grad School who also administers our BePress Digital Commons and I are getting together to do just that. One of the reasons we don't want to use the Inactive/Active states is that our universe is a consortium one where users from different institutions have access and use inactive for other purposes. This would mean that the Grad School would have to sort through the inactive list in the simple workflow to find what they're looking for. Also, they have indicated that they would like to be the ones to have it published or uploaded. When we have something, I'll definitely share it.

**Comment by dmoses** [comment]
Right ... as an alternative you could apply an XACML policy on ingest with manage / view of the object limited to a role of etd_approver ... and the etd_approver role would update the policy once approved. You could create a rule that sent an email to those with the etd_approver role on ingest. ... or something like that :)

**Comment by uconnjeustis** [comment]
Clever! Thanks Donald.
