### ISSUE TITLE
Templates for Citation and Thesis cModels

### ISSUE THREAD

**Issue by BCDigIR** [islandora-interest-groups/Islandora-IR-Interest-Group#15]
The Scholar module currently does not have Drupal template files (.tpl.php) for the Citation and Thesis cModel page displays. These displays are instead built in islandora_scholar/includes/utilities.inc. This makes it very difficult to make modifications to the layout of these pages and sets it apart from the other solution packs in how it is structured. 

It would be a great improvement to add Drupal template files to this module; however, I am not sure how much restructuring would need to be done or what the original reasons were for building it differently.

**Comment by bryjbrown** [comment]
We did this at FSU, see if it works for you: https://github.com/FLVC/islandora_scholar_templates

**Comment by bondjimbond** [comment]
+1
