### ISSUE TITLE
Metrics WG Use Cases

### ISSUE THREAD

**Issue by bryjbrown** [islandora-interest-groups/Islandora-IR-Interest-Group#21]
This issue will be for collecting use cases for "scholarly" metrics in an IR. "Scholarly" metrics simply denotes metrics that are of value in an academic context, as opposed to more traditional site metrics like bounce rates, browsers, etc.

I'll start:
- FSU needs accurate counts of views and downloads that include the time and IP address of each view/download event (we're taking care of this with the [Islandora Usage Stats](https://github.com/islandora/islandora_usage_stats) module). We currently have this working, along with another [helper module](https://github.com/flvc/islandora_usage_stats_callbacks) that exposes views/downloads data as JSON through an API.
- Once we have views/downloads being counted, we want to display the views/downloads for a particular object in it's template so that users can know how much usage that item gets. We ALMOST have this working through a mixture of the [Islandora Scholar Templates](https://github.com/flvc/islandora_scholar_templates) module and citation/thesis templates that make calls to the view/downloads API (listed above).
- Faculty want readership reports emailed to them at the start of the month showing the total views/downloads and last month's views/downloads for every object they have in the IR. We're currently working on this, but the particular way that we're implementing it won't work for other institutions (sorry! but rolling this into an Islandora module that others can use is planned).
- Faculty want a readership dashboard that will show them, at any given time, the total and monthly views/downloads for all of their objects and chart those monthly totals on a pretty graph. We are only beginning to think about how this could be done, but it would most likely involve creating an Entities SP record for faculty and adding a tab to their template calls the view/downloads data and charts it with some fancypants javascript graph library.
- Finally, faculty also want some sort of altmetrics integration. I don't understand what that means, how it would work or whether its by author or by object, but we'll be exploring this in the coming months.

**Comment by dmoses** [comment]
there's an islandora_altmetrics [1] module already ... it might meet your needs.

[1] https://github.com/Islandora/islandora_altmetrics

**Comment by dmoses** [comment]
we've got a dashboard for users in our data.upei.ca site and we're using views and blocks fairly heavily. If the data is accessible via views, then a dashboard is definitely doable ... our linkage is the person's username ... and that is also present in both their islandora objects and drupal nodes.

![image](https://cloud.githubusercontent.com/assets/494152/12660766/d8b10564-c5eb-11e5-8807-0e2a554f75a5.png)
