### ISSUE TITLE
Decouple the Scholar module in smaller submodules for maintainability

### ISSUE THREAD

**Issue by bryjbrown** [islandora-interest-groups/Islandora-IR-Interest-Group#8]
Part of what makes talking about the Scholar module difficult is that it has so many features where other Islandora modules tend to do one thing.

Possible submodules that could be teased out into their own thing:
- citation cmodel solution pack
- thesis cmodel solution pack
- embargoes
- dynamic citation display (Citeproc/CSL)
- sherpa/romeo checking
- google scholar integration
- specialty imports (pubmed IDs, RIS, endnote)
- DOI integration

All of these could easily be their own standalone module, which would give users more flexibility in choosing the exact functionality they want, and make it much simpler to make enhancements to any specific feature.

**Comment by dmoses** [comment]
+1 dmoses

**Comment by akosavic** [comment]
+1 makes a lot of sense to me!

**Comment by bondjimbond** [comment]
+1

**Comment by bryjbrown** [comment]
Okay, so out of all the things Scholar currently does, what should be the first thing(s) to be decoupled? 

I'm thinking that the cmodels should be first, with embargoes and Google Scholar integration being close seconds.

**Comment by DonRichards** [comment]
+1

**Comment by bryjbrown** [comment]
As a result of the IR IG call today, we decided that this would be a fool's errand. It would require an incredible amount of time and has a high potential of breaking backwards compatibility, especially with CLAW on the horizon. Lets just take our lessons learned and make sure we design things properly in CLAW.
